version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: student-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend # ✅ build from local backend folder
    image: student-backend
    container_name: student-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend # ✅ build from local frontend folder
    image: student-frontend
    container_name: student-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql-data:
